name: Package CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3

    - name: Install dependencies
      run: pip install git+https://github.com/happer64bit/ginz-cli#egg=ginz
    
    - name: Installion Some Dependencies
      run: pip install tqdm && pip install GitPython && pip install requests
    
    - name: Run the pip package
      run: python -m ginz --version
